# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from worker import mqttguide_pb2 as mqttguide__pb2


class MqttGuideStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DingDong = channel.unary_unary(
                '/mqttguide.MqttGuide/DingDong',
                request_serializer=mqttguide__pb2.DingDongArgs.SerializeToString,
                response_deserializer=mqttguide__pb2.DingDongRet.FromString,
                )


class MqttGuideServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DingDong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MqttGuideServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DingDong': grpc.unary_unary_rpc_method_handler(
                    servicer.DingDong,
                    request_deserializer=mqttguide__pb2.DingDongArgs.FromString,
                    response_serializer=mqttguide__pb2.DingDongRet.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mqttguide.MqttGuide', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MqttGuide(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DingDong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mqttguide.MqttGuide/DingDong',
            mqttguide__pb2.DingDongArgs.SerializeToString,
            mqttguide__pb2.DingDongRet.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
